In [6]:
#假设我们想对函数y=2x^Tx关于列向量x求导
import torch

x = torch.arange(4.0)  # 创建一个列向量，并且需要对它求导
x

tensor([0., 1., 2., 3.])

In [7]:
#先创建一个地方存梯度
x.requires_grad_(True)  # 等价于：x = torch.arange(4.0, requires_grad=True)
x.grad # 目前没有梯度,默认是None

y = 2 * torch.dot(x, x) #算函数值
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward() # 反向传播，计算梯度
x.grad # 输出梯度

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4 * x

tensor([True, True, True, True])

In [ ]:
# 默认情况下，pytorch会累积梯度，即每次调用backward()都会将计算得到的梯度加到之前的梯度上，而不是替换掉之前的梯度。
x.grad.zero_() # 梯度清零
y = x.sum() # 计算新的函数值
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [ ]:
# 对非标量调用‘backward’，需要传入一个gradient参数，该参数指定了梯度的形状。对于标量函数，梯度默认为1。
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [16]:
x.grad.zero_()
y = x * x
u = y.detach() # 生成一个新的张量u与y共享数据但不需要梯度(常量)
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [17]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [22]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

print(a.grad == d / a)

tensor(True)
