In [2]:
import torch

x = torch.tensor([2.0])
y = torch.tensor([3.0])
x+y, x-y, x*y, x/y, x**y

(tensor([5.]), tensor([-1.]), tensor([6.]), tensor([0.6667]), tensor([8.]))

In [3]:
z = torch.arange(5)
print(z)

tensor([0, 1, 2, 3, 4])


In [ ]:
print(z[1], len(z), z.shape)

tensor(1) 5 torch.Size([5])


In [5]:
A = torch.arange(20).reshape(4, 5)
print(A,"\n")
print(A.T)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]) 

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])


In [6]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B,"\n")
print(B ==B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]]) 

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [7]:
Z = torch.arange(24).reshape(3, 4, 2)
Z

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

In [ ]:
C = torch.arange(20, dtype=torch.float32).reshape(4, 5)
D = C.clone() #通过分配新内存，将C的一个副本给D
C, C+D

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]))

In [11]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [12]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [17]:
W = torch.arange(40).reshape(2, 5, 4)
print(W)
print(W.shape) 
print(W.sum())

W_sum_axis0 = W.sum(axis=0)
print(W_sum_axis0) 
print(W_sum_axis0.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
torch.Size([2, 5, 4])
tensor(780)
tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])
torch.Size([5, 4])


In [19]:
W_sum_axis1 = W.sum(axis=1) #压缩行，每个矩阵，每行按列对应相加
print(W_sum_axis1)
print(W_sum_axis1.shape)


W_sum_axis2 = W.sum(axis=2) #压缩列，每个矩阵，每列按行对应相加
print(W_sum_axis2)
print(W_sum_axis2.shape)

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])
torch.Size([2, 4])
tensor([[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]])
torch.Size([2, 5])


In [ ]:
print(W.sum(axis=[0, 1])) #两个维度求和
print(W.sum(axis=[0, 1]).shape) #前两维已经压缩，只剩第三维“4”

tensor([180, 190, 200, 210])
torch.Size([4])


In [ ]:
print(W.float().mean()) #W.float()将整数张量转换为浮点数张量，mean()计算所有元素的平均值
print(W.float().sum() / W.numel())

tensor(19.5000)
tensor(19.5000)


In [ ]:
print(W.float().mean(axis=0)) #沿行的方向求平均，即每一列求平均
print(W.float().sum(axis=0) / W.shape[0]) #第0维的长度是2，除以2得到平均值

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])
tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])


In [ ]:
sum_W = W.sum(axis=0, keepdim=True) #保留被压缩的维度，便于后续广播
print(sum_W)

tensor([[[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])


In [ ]:
W / sum_W #由于上面保留了维度，0维没有被压缩，所以可以直接进行广播运算

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

In [36]:
print(W)
print(W.cumsum(axis=0)) #沿着第0维累积求和

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])


In [38]:
y = torch.ones(4, dtype=torch.float32)
print(x, y, torch.dot(x, y))
print(torch.sum(x * y) == torch.dot(x, y))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor(True)


In [ ]:
A.T.shape, x.shape, torch.mv(A.T.float(), x) #torch.mv()函数执行矩阵向量乘法，A.T.float()将A的转置转换为浮点数张量，x是一个向量

(torch.Size([5, 4]), torch.Size([4]), tensor([70., 76., 82., 88., 94.]))

In [46]:
D = torch.ones(5, 3)
torch.mm(A.float(), D) #torch.mm()函数执行矩阵乘法，A.float()将A转换为浮点数张量，D是一个矩阵

tensor([[10., 10., 10.],
        [35., 35., 35.],
        [60., 60., 60.],
        [85., 85., 85.]])

In [ ]:
u = torch.tensor([3.0 , 4.0])
torch.norm(u) #L2范数，求长度

tensor(5.)

In [48]:
torch.abs(u).sum() #L1范数，求绝对值之和

tensor(7.)

In [ ]:
torch.norm(torch.ones((4, 9))) 

tensor(6.)